/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.github.daggerok

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class CallByValueVsCallByNameSuite extends AnyFunSuite {
  test("should call by value") {
    var res1: Long = 0
    var res2: Long = 0
    def callByValue(nanoSeconds: Long): Unit = {
      res1 = nanoSeconds
      res2 = nanoSeconds
      println(s"call by value 1: $nanoSeconds")
      println(s"call by value 2: $nanoSeconds")
    }
    callByValue(System.nanoTime())
    assert(res1 == res2)
  }

  test("should call by name") {
    var res1: Long = 0
    var res2: Long = 0
    def callByValue(nanoSeconds: => Long): Unit = {
      res1 = nanoSeconds
      res2 = nanoSeconds
      println(s"call by name 1: $nanoSeconds")
      println(s"call by name 2: $nanoSeconds")
    }
    callByValue(System.nanoTime())
    assert(res1 != res2)
  }
}
