/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.github.daggerok

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

import scala.annotation.tailrec

@RunWith(classOf[JUnitRunner])
class TailrecSuite extends FunSuite {
  test("should concat string n times by using tail recursion") {
    @tailrec
    def concatTimes(str: String, n: Int, acc: String = ""): String =
      if (n <= 0) acc else concatTimes(str, n - 1, s"$str$acc")
    assert("aaa" == concatTimes("a", 3))
  }

  test("should concat string using inner tail recursive function") {
    def concatTimes(string: String, times: Int): String = {
      @tailrec
      def loop(accumulator: String, times: Int): String =
        if (times <= 0) accumulator
        else loop(s"$string$accumulator", times - 1)
      loop("", times)
    }
    assert("bb" == concatTimes("b", 2))
  }
}
