# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: 'GitHub actions CI build'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      check-updates:
        description: 'Check Gradle versions updates'
        required: true
        default: '.'
jobs:
  dependency-updates:
    if: github.event.inputs.check-updates != '' # disable local deploy triggered automatically as not needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle-scala-application-howto
        id: gradle-scala-application-howto
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew dependencyUpdates -Drevision=release
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle-scala-application-howto
        id: gradle-scala-application-howto
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle-scala-application-howto
        id: gradle-scala-application-howto
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - name: Cache gradle-scala-application-howto npm
        id: gradle-scala-application-howto-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew npm_i npm_run_gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .vuepress/dist # The folder the action should deploy.
